name: Rust CI and Release

on:
  push:
    分支: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # 添加标签触发条件，用于创建 Releases
  push:
    标签:
      - 'v*.*.*'  # 匹配语义化版本标签，如 v1.0.0

env:
  CARGO_TERM_COLOR: always
  PROJECT_NAME: your-project-name  # 替换为你的项目名称

jobs:
  build_and_test:
    strategy:
      matrix:
        platform: [ubuntu-latest， windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    name: Build and Test on ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: actions-rust-lang/setup-rust@v1
      with:
        rust-version: stable
    
    - name: Build
      run: cargo build --verbose
    
    - name: Run tests
      run: cargo test --verbose

  create_release:
    needs: build_and_test  # 依赖构建任务
    if: startsWith(github.ref, 'refs/tags/v')  # 仅在标签推送时运行
    runs-on: ubuntu-latest
    name: Create Release
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Install Rust
      uses: actions-rust-lang/setup-rust@v1
      with:
        rust-version: stable
        targets: x86_64-unknown-linux-gnu, x86_64-pc-windows-msvc, x86_64-apple-darwin
    
    - name: Build Release Binaries
      run: |
        cargo build --release --target x86_64-unknown-linux-gnu
        cargo build --release --target x86_64-pc-windows-msvc
        cargo build --release --target x86_64-apple-darwin
        
    - name: Package Binaries
      run: |
        mkdir -p release
        # Linux
        tar czf release/${{ env.PROJECT_NAME }}-linux-x86_64.tar.gz -C target/x86_64-unknown-linux-gnu/release ${{ env.PROJECT_NAME }}
        # Windows
        zip -j release/${{ env.PROJECT_NAME }}-windows-x86_64.zip target/x86_64-pc-windows-msvc/release/${{ env.PROJECT_NAME }}.exe
        # macOS
        tar czf release/${{ env.PROJECT_NAME }}-macos-x86_64.tar.gz -C target/x86_64-apple-darwin/release ${{ env.PROJECT_NAME }}
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        
    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/${{ env.PROJECT_NAME }}-linux-x86_64.tar.gz
        asset_name: ${{ env.PROJECT_NAME }}-linux-x86_64.tar.gz
        asset_content_type: application/gzip
        
    - name: Upload Windows Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/${{ env.PROJECT_NAME }}-windows-x86_64.zip
        asset_name: ${{ env.PROJECT_NAME }}-windows-x86_64.zip
        asset_content_type: application/zip
        
    - name: Upload macOS Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/${{ env.PROJECT_NAME }}-macos-x86_64.tar.gz
        asset_name: ${{ env.PROJECT_NAME }}-macos-x86_64.tar.gz
        asset_content_type: application/gzip
